# Generated by Django 6.0.4 on 2026-04-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
