# Generated by Django 6.0.4 on 2026-04-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_review_wishlist_wishlistitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("wishlist", "product")},
        ),
    ]
