# Generated by Django 6.0.4 on 2026-07-01 23:33

import django.db.models.deletion
from django.db import migrations, models


def copy_product_images(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductImage = apps.get_model("products", "ProductImage")

    for product in Product.objects.exclude(image=""):
        if product.image:
            ProductImage.objects.create(
                product=product,
                image=product.image,
                is_main=True,
            )


def remove_copied_product_images(apps, schema_editor):
    ProductImage = apps.get_model("products", "ProductImage")
    ProductImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("is_main", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.RunPython(copy_product_images, remove_copied_product_images),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
