# Generated by Django 6.0.4 on 2026-07-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-is_main", "id"]},
        ),
    ]
