# Generated by Django 6.0.4 on 2026-06-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heroslide",
            options={"ordering": ["order"]},
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
