# Generated by Django 6.0.4 on 2026-08-22 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_promotionbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, help_text='Upload an MP4 or WebM video. Use a compressed web video for fast loading.', null=True, upload_to='hero/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection hero video',
                'verbose_name_plural': 'Collection hero video',
            },
        ),
    ]
