# Generated by Django 6.0.4 on 2026-04-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='cod', max_length=20),
        ),
    ]
