# Generated by Django 6.0.6 on 2026-06-11 22:02

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_contactmessage_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
