# Generated by Django 6.0.4 on 2026-06-24 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_city_remove_contactmessage_subject_and_more"),
        ("users", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.city"
            ),
        ),
    ]
