# Generated by Django 6.0.4 on 2026-06-21 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("order_update", "Order Update"),
                            ("order_cancel", "Order Cancel"),
                            ("product_update", "Product Update"),
                            ("product_create", "Product Create"),
                            ("user_update", "User Update"),
                            ("login", "Admin Login"),
                            ("logout", "Admin Logout"),
                            ("stock_update", "Stock Update"),
                            ("security_event", "Security Event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("object_id", models.CharField(blank=True, max_length=50, null=True)),
                ("object_type", models.CharField(blank=True, max_length=50, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
